name: Portfolio Deployment

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@vi
    
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@vi
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
  
    - name: Deploy static site to $3 bucket
      run: aws S3 sync. S3://tws-portfolio321 --delete
